- name: Check SSH connectivity to all hosts
  hosts: all
  gather_facts: no
  tasks:

    - name: Pause for 2 minutes for VMs to be up
      ansible.builtin.pause:
        minutes: 2

    - name: Wait for SSH port to become available
      wait_for:
        host: "{{ ansible_host | default(inventory_hostname) }}"  # Ensures correct host is used
        port: 22  # SSH port
        state: started  # Wait for the port to be open
        timeout: 300  # Maximum wait time
        delay: 10  # Wait 10 seconds before the first attempt
      retries: 10
      delay: 60
      register: ssh_ready
      until: ssh_ready is succeeded
