- hosts: microk8s_HA
  gather_facts: no
  tasks:

    - name: Write kubeconfig
      shell: microk8s config > /tmp/kubeconfig
      args:
        executable: /bin/bash
      run_once: true
      delegate_to: "{{groups['microk8s_HA'][0]}}"

    - name: Fetch kubeconfig
      fetch:
        src: /tmp/kubeconfig
        dest: kubeconfig
        flat: true
      run_once: true
      delegate_to: "{{groups['microk8s_HA'][0]}}"
