- hosts: all
  roles:
    - role: ansible_role_microk8s
      vars:
        microk8s_enable_HA: true
        add_workers_to_hostfile: true
        microk8s_plugins:
          rbac: true
          ingress: true
          metrics-server: true
          cert-manager: true
          community: true
          nfs: true
