apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVWkc1SzZpcXRLV2lVNlI5KzNsb0F3VHl1SEpJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXlNVEF5TlRBek5ESTFORm9YRFRNeQpNVEF5TWpBek5ESTFORm93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE1ZmN6MDc3YTdpeEFCZzRteHltc1Q4TmZXNW9Pb245ZVZsL2QKcm01Yi9TaXp1YTFsYkVlQkZBdlIveldMTkVWWXhmbFpyM0VxaWxXRlJrdUxsNnBFS3RLaWtYVTB2SmNDbmg0SgpkUVQwYXh5d0tRUGY2bkRBTzNGdWJORHd1VzZHTkM2QnNjNUtqMGt0UG45V29LZkxkdjFhYTVVb3crNUkzR2NlClJuajgwZzdTd1gwTnBRREdNSXBQSkhjTnJYVmgyaTdLTGhYQUJtc01MMHlEZzZEUlBoWlpkaWtrZTRCejdxaFIKb3ZUTjVTTGJJQ0hJbC9TSVpqMFJ4Q0pFTGdjV1BUOVdvdUU5eG1yU1BwMUw3QVZiQlhjZUJ1TGoySmNoc2lTOQpXWHoxUklqcUkwUXFhbFBMeWlhc3VZRnhMeDk4bUJnOFUrbGZhVzhVMUdSaWRwRitaUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVXBIVG9USUFPelhac21oMENDeWp3UGZILzg4Z3dId1lEVlIwakJCZ3dGb0FVcEhUb1RJQU8Kelhac21oMENDeWp3UGZILzg4Z3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBT0hUK3MzVHBkVDI4S0h0a2g2WEJJQkczUW93TkQ4OVBlT2I4cE1GcStDUktTYWEzR1dkR1o3STloczl1CmVqYzdETkgrcVI4TmU3WjU5UDRNUnkzYWZpbDRLMkQ1M0ZNZXlQS29rdkdhN0I4a2ZrWE5PajdyUmpkc1JEaGIKMjA2cGx1QzJBbzNnaDdtWHNDVGRyZmFoUmJFZjlRcXkrdWNGb3ErSXNJck5qOXI5MXlOTVRrT2NkT05VTjdCNgoxWG9tT3FFNjdmRUNtMThyWVJqZjNDckgra1Q4VURBYzhDQm9zSWtNWHZnc2ttVkUxaGo4aHVnM3oybHcxeWJnCkw0RThvTDhkdldxVzVRSFNPWTJ0V3RyMWltS1oxMjZOdzRUUlpGMU1WMVVza21HRVlQaDdKanBaYlpCNittWmQKSk1jeVdDVmtIZmZQWEhiMG85bndCVUlxWVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://216.48.177.171:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: bzV1OW1yRUp6UFZWeWFxSzZndFJjL0dsaUhSSUR4SGJUVVF6eXR1c1BYbz0K
