- hosts: microk8s_HA
  gather_facts: no
  become: yes
  tasks:

    - name: Remove nodes
      shell: "microk8s remove-node {{ item }}"
      loop: "{{ nodes.split(',') }}"
      run_once: true
      delegate_to: "{{groups['microk8s_HA'][0]}}"
